name: firstapp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 Checkout Repository 
        uses: actions/checkout@v4
      - name: step 2 hello world
        run: echo "hello ji... "
        shell: bash

  second-job: 
    runs-on: ubuntu-latest
    steps:
      - name: step1 checkout Repository
        uses: actions/checkout@v4
      - name: step2 goodbye
        run: echo "goodbye..."
        shell: bash
      
  

