name: Add Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout for potential future use

      # Create comment using action (preferred method)
      - name: Create comment using 'create-or-update-comment' action
        uses: peter-evans/create-or-update-comment@v4  # Update if necessary
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment with GitHub Markdown:

            - **Bold** text
            - *Italic* text
            - `Code block`
            - Link to [create-or-update-comment action][1]

      # Alternatively, create comment with GitHub API (secure)
      - name: Create comment using GitHub API (secure)
        run: |
          gh api -X POST \
            "https://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}/comments" \
            -f body='Comment from secure GitHub API call with basic formatting (e.g., bold, italics)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
