name: create a comment on new issues.

on:
  issues:
    types: [opened]
    
jobs:
  first-comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context."
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
    
